import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import AppLayout from "@/components/layouts/app-layout";
import ThemeProvider from "@/components/providers/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <ThemeProvider>
        <AppLayout>{children}</AppLayout>
      </ThemeProvider>
    </html>
  );
}
